default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  host: postgres
  port: 5432

development:
  <<: *default
  database: image_service_development
test:
  <<: *default
  database: image_service_test
production:
  <<: *default
  database: image_service_production
  username: image_service
  password: <%= ENV['IMAGE_SERVICE_DATABASE_PASSWORD'] %>
